services:
  # Backend Service
  backend:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app

  # Database
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dappdb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
