version: "3.9"
services:

  # Database
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dappdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

    # Backend Service
    backend:
      build: ./backend
      restart: always
      depends_on:
        - db
      environment:
        DATABASE_URL: postgres://postgres:postgres@db:5432/dappdb
        STELLAR_NETWORK: testnet
      ports:
        - "4000:4000"

  
volumes:
  db_data:
